-- Dummy data generated by ChatGPT
-- Inserting dummy data for employers
INSERT INTO employers (employer_name) VALUES
('ABC Company'),
('XYZ Corporation'),
('123 Enterprises'),
('Tech Solutions Inc.'),
('Global Innovations Ltd.'),
('Sunshine Industries'),
('Peak Performance Group'),
('Evergreen Enterprises'),
('Bright Future Co.'),
('Pioneer Technologies');

-- Inserting dummy data for jobs
-- Employer 1: ABC Company
INSERT INTO jobs (job_title, job_description, job_location, job_salary_min, job_salary_max, employer_id) VALUES
('Software Engineer', 'Develop and maintain software applications', 'New York', 60000.00, 80000.00, 1),
('Marketing Manager', 'Plan and execute marketing campaigns', 'Los Angeles', 50000.00, 70000.00, 1),
('Financial Analyst', 'Analyze financial data and prepare reports', 'Chicago', 55000.00, 75000.00, 1),
('Data Analyst', 'Collect and analyze data to inform business decisions', 'San Francisco', 55000.00, 75000.00, 1),
('Sales Representative', 'Sell company products and services to potential customers', 'Houston', 45000.00, 65000.00, 1),
('Customer Service Representative', 'Assist customers with inquiries and issues', 'Miami', 40000.00, 60000.00, 1),
('Human Resources Coordinator', 'Support HR department with administrative tasks', 'Atlanta', 45000.00, 65000.00, 1),
('Project Manager', 'Oversee and coordinate project activities', 'Denver', 60000.00, 80000.00, 1),
('Web Developer', 'Design and develop websites and web applications', 'Seattle', 55000.00, 75000.00, 1),
('Accountant', 'Manage financial records and prepare reports', 'Dallas', 50000.00, 70000.00, 1);

-- Employer 2: XYZ Corporation
INSERT INTO jobs (job_title, job_description, job_location, job_salary_min, job_salary_max, employer_id) VALUES
('Data Scientist', 'Analyze large datasets and develop predictive models', 'San Francisco', 70000.00, 90000.00, 2),
('Graphic Designer', 'Create visual concepts and designs', 'Seattle', 45000.00, 65000.00, 2),
('HR Manager', 'Manage recruitment and employee relations', 'Boston', 55000.00, 75000.00, 2),
('Software Developer', 'Develop and maintain software applications', 'New York', 60000.00, 80000.00, 2),
('Sales Manager', 'Lead and manage sales team to achieve targets', 'Los Angeles', 65000.00, 85000.00, 2),
('Financial Advisor', 'Provide financial advice and investment strategies', 'Chicago', 60000.00, 80000.00, 2),
('Operations Coordinator', 'Coordinate day-to-day operations activities', 'Houston', 50000.00, 70000.00, 2),
('Content Writer', 'Create engaging content for marketing materials', 'Miami', 40000.00, 60000.00, 2),
('Quality Assurance Analyst', 'Test software applications for quality and functionality', 'Atlanta', 55000.00, 75000.00, 2),
('Product Manager', 'Develop and execute product strategies', 'Denver', 70000.00, 90000.00, 2);


-- Employer 3: 123 Enterprises
INSERT INTO jobs (job_title, job_description, job_location, job_salary_min, job_salary_max, employer_id) VALUES
('Customer Success Manager', 'Ensure customer satisfaction and retention', 'San Francisco', 55000.00, 75000.00, 3),
('Frontend Developer', 'Design and develop user interfaces for web applications', 'Seattle', 60000.00, 80000.00, 3),
('Operations Manager', 'Oversee daily operations and improve efficiency', 'Chicago', 65000.00, 85000.00, 3),
('Digital Marketing Specialist', 'Plan and execute digital marketing campaigns', 'New York', 50000.00, 70000.00, 3),
('Business Analyst', 'Analyze business processes and recommend improvements', 'Los Angeles', 55000.00, 75000.00, 3),
('Technical Support Engineer', 'Provide technical assistance to customers', 'Boston', 45000.00, 65000.00, 3),
('Content Marketing Manager', 'Develop and implement content marketing strategies', 'Houston', 60000.00, 80000.00, 3),
('Software Tester', 'Test software applications for bugs and defects', 'Miami', 45000.00, 65000.00, 3),
('Supply Chain Coordinator', 'Coordinate logistics and inventory management', 'Atlanta', 50000.00, 70000.00, 3),
('UX/UI Designer', 'Create intuitive user experiences and interfaces', 'Denver', 55000.00, 75000.00, 3);

-- Employer 4: Tech Solutions Inc.
INSERT INTO jobs (job_title, job_description, job_location, job_salary_min, job_salary_max, employer_id) VALUES
('Software Engineer', 'Develop and maintain software applications', 'San Francisco', 70000.00, 90000.00, 4),
('Network Administrator', 'Manage and maintain computer networks', 'Seattle', 60000.00, 80000.00, 4),
('Cybersecurity Analyst', 'Protect computer systems from cyber threats', 'Chicago', 65000.00, 85000.00, 4),
('IT Project Manager', 'Plan and oversee IT projects from initiation to completion', 'New York', 75000.00, 95000.00, 4),
('Database Administrator', 'Manage and optimize databases', 'Los Angeles', 65000.00, 85000.00, 4),
('Systems Analyst', 'Analyze and improve computer systems', 'Boston', 60000.00, 80000.00, 4),
('Cloud Solutions Architect', 'Design and implement cloud-based solutions', 'Houston', 80000.00, 100000.00, 4),
('AI/Machine Learning Engineer', 'Develop AI and machine learning algorithms', 'Miami', 75000.00, 95000.00, 4),
('DevOps Engineer', 'Automate and streamline software development processes', 'Atlanta', 70000.00, 90000.00, 4),
('Technical Support Specialist', 'Provide technical assistance to clients', 'Denver', 55000.00, 75000.00, 4);

-- Employer 5: Global Innovations Ltd.
INSERT INTO jobs (job_title, job_description, job_location, job_salary_min, job_salary_max, employer_id) VALUES
('Research Scientist', 'Conduct scientific research and experiments', 'San Francisco', 80000.00, 100000.00, 5),
('Product Designer', 'Design innovative products and prototypes', 'Seattle', 65000.00, 85000.00, 5),
('Business Development Manager', 'Identify new business opportunities and partnerships', 'Chicago', 70000.00, 90000.00, 5),
('UX/UI Designer', 'Create user-centric designs for digital products', 'New York', 75000.00, 95000.00, 5),
('Project Coordinator', 'Coordinate project activities and resources', 'Los Angeles', 55000.00, 75000.00, 5),
('Quality Assurance Engineer', 'Ensure product quality through testing and analysis', 'Boston', 60000.00, 80000.00, 5),
('Technical Writer', 'Create technical documentation and user manuals', 'Houston', 50000.00, 70000.00, 5),
('Environmental Engineer', 'Develop solutions to environmental problems', 'Miami', 65000.00, 85000.00, 5),
('Marketing Analyst', 'Analyze market trends and consumer behavior', 'Atlanta', 60000.00, 80000.00, 5),
('Software Architect', 'Design and oversee the implementation of software systems', 'Denver', 85000.00, 105000.00, 5);

-- Employer 6: Sunshine Industries
INSERT INTO jobs (job_title, job_description, job_location, job_salary_min, job_salary_max, employer_id) VALUES
('Production Supervisor', 'Oversee manufacturing processes and staff', 'San Francisco', 55000.00, 75000.00, 6),
('Electrical Engineer', 'Design and develop electrical systems and components', 'Seattle', 70000.00, 90000.00, 6),
('Supply Chain Manager', 'Manage supply chain operations and logistics', 'Chicago', 75000.00, 95000.00, 6),
('Mechanical Designer', 'Create mechanical designs and blueprints', 'New York', 60000.00, 80000.00, 6),
('Customer Support Manager', 'Manage customer support team and operations', 'Los Angeles', 65000.00, 85000.00, 6),
('Manufacturing Engineer', 'Improve manufacturing processes and efficiency', 'Boston', 70000.00, 90000.00, 6),
('Quality Control Inspector', 'Inspect products to ensure they meet quality standards', 'Houston', 50000.00, 70000.00, 6),
('Health and Safety Coordinator', 'Implement health and safety programs and policies', 'Miami', 55000.00, 75000.00, 6),
('Industrial Engineer', 'Optimize production processes and workflow', 'Atlanta', 65000.00, 85000.00, 6),
('Operations Manager', 'Manage day-to-day operations and resources', 'Denver', 75000.00, 95000.00, 6);

-- Employer 7: Peak Performance Group
INSERT INTO jobs (job_title, job_description, job_location, job_salary_min, job_salary_max, employer_id) VALUES
('Fitness Trainer', 'Provide personalized fitness training to clients', 'San Francisco', 45000.00, 65000.00, 7),
('Nutritionist', 'Develop customized nutrition plans for clients', 'Seattle', 50000.00, 70000.00, 7),
('Physical Therapist', 'Provide rehabilitation services to patients', 'Chicago', 60000.00, 80000.00, 7),
('Sports Psychologist', 'Provide mental skills training to athletes', 'New York', 70000.00, 90000.00, 7),
('Athletic Coach', 'Coach athletes in specific sports techniques and strategies', 'Los Angeles', 55000.00, 75000.00, 7),
('Exercise Physiologist', 'Conduct exercise tests and prescribe fitness programs', 'Boston', 55000.00, 75000.00, 7),
('Wellness Coordinator', 'Plan and implement wellness programs for organizations', 'Houston', 50000.00, 70000.00, 7),
('Sports Medicine Physician', 'Diagnose and treat sports-related injuries', 'Miami', 80000.00, 100000.00, 7),
('Strength and Conditioning Coach', 'Design and implement strength training programs', 'Atlanta', 60000.00, 80000.00, 7),
('Fitness Center Manager', 'Oversee operations of a fitness facility', 'Denver', 65000.00, 85000.00, 7);

-- Employer 8: Bright Future Co.
INSERT INTO jobs (job_title, job_description, job_location, job_salary_min, job_salary_max, employer_id) VALUES
('Educational Consultant', 'Provide guidance on educational planning and career paths', 'San Francisco', 60000.00, 80000.00, 8),
('Career Coach', 'Assist individuals in exploring career options and setting goals', 'Seattle', 55000.00, 75000.00, 8),
('Academic Advisor', 'Advise students on course selection and academic planning', 'Chicago', 50000.00, 70000.00, 8),
('Tutor', 'Provide personalized academic support to students', 'New York', 45000.00, 65000.00, 8),
('Guidance Counselor', 'Offer counseling and support to students in academic and personal matters', 'Los Angeles', 55000.00, 75000.00, 8),
('Training Coordinator', 'Develop and deliver training programs for employees', 'Boston', 60000.00, 80000.00, 8),
('Youth Program Coordinator', 'Plan and oversee programs for youth development', 'Houston', 50000.00, 70000.00, 8),
('Curriculum Developer', 'Design and develop educational materials and programs', 'Miami', 55000.00, 75000.00, 8),
('Instructional Designer', 'Design and develop instructional materials for e-learning', 'Atlanta', 60000.00, 80000.00, 8),
('School Administrator', 'Manage day-to-day operations of a school or educational institution', 'Denver', 70000.00, 90000.00, 8);

-- Employer 9: Evergreen Enterprises
INSERT INTO jobs (job_title, job_description, job_location, job_salary_min, job_salary_max, employer_id) VALUES
('Environmental Specialist', 'Assess and mitigate environmental impacts', 'San Francisco', 60000.00, 80000.00, 9),
('Sustainability Coordinator', 'Develop and implement sustainability initiatives', 'Seattle', 55000.00, 75000.00, 9),
('Conservation Scientist', 'Research and implement strategies for natural resource conservation', 'Chicago', 65000.00, 85000.00, 9),
('Urban Planner', 'Design and manage urban development projects', 'New York', 70000.00, 90000.00, 9),
('Forestry Technician', 'Manage and maintain forests and natural resources', 'Los Angeles', 50000.00, 70000.00, 9),
('Ecologist', 'Study ecosystems and their interactions', 'Boston', 65000.00, 85000.00, 9),
('Environmental Educator', 'Educate the public on environmental issues and conservation', 'Houston', 45000.00, 65000.00, 9),
('Wildlife Biologist', 'Study and manage wildlife populations and habitats', 'Miami', 55000.00, 75000.00, 9),
('Environmental Engineer', 'Design and implement solutions for environmental problems', 'Atlanta', 70000.00, 90000.00, 9),
('Park Ranger', 'Manage and maintain natural parks and recreational areas', 'Denver', 50000.00, 70000.00, 9);

-- Employer 10: Pioneer Technologies
INSERT INTO jobs (job_title, job_description, job_location, job_salary_min, job_salary_max, employer_id) VALUES
('Software Developer', 'Design and develop software applications', 'San Francisco', 70000.00, 90000.00, 10),
('Data Analyst', 'Analyze data and generate insights for decision-making', 'Seattle', 60000.00, 80000.00, 10),
('Network Engineer', 'Design and implement computer networks', 'Chicago', 65000.00, 85000.00, 10),
('Systems Administrator', 'Manage and maintain IT infrastructure', 'New York', 75000.00, 95000.00, 10),
('Database Administrator', 'Manage and optimize databases', 'Los Angeles', 70000.00, 90000.00, 10),
('Cybersecurity Specialist', 'Protect computer systems from cyber threats', 'Boston', 80000.00, 100000.00, 10),
('IT Project Manager', 'Plan and oversee IT projects', 'Houston', 75000.00, 95000.00, 10),
('Web Developer', 'Design and develop websites and web applications', 'Miami', 60000.00, 80000.00, 10),
('UI/UX Designer', 'Create intuitive user interfaces and experiences', 'Atlanta', 65000.00, 85000.00, 10),
('Cloud Solutions Architect', 'Design and implement cloud-based solutions', 'Denver', 85000.00, 105000.00, 10);
